version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing Terraform..."
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - echo "Validating Terraform configuration..."
      - terraform init
      - terraform validate
  build:
    commands:
      - echo "Starting build phase..."
      - echo "Applying Terraform configuration..."
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan
