version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing Terraform"
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo tee /etc/apt/trusted.gpg.d/hashicorp.asc
      - sudo apt-get update
      - sudo apt-get install -y terraform
      - mv terraform /usr/local/bin/
      - terraform --version
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - echo "Validating Terraform configuration..."
      - terraform init
      - terraform validate
  build:
    commands:
      - echo "Starting build phase..."
      - echo "Applying Terraform configuration..."
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan
